/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.listagem;

import DAO.AplicacaoDAO;
import DAO.AplicacaoDefensivoDAO;
import DAO.EntregaDAO;
import entities.Aplicacao;
import entities.AplicacaoDefensivo;
import entities.Defensivo;
import entities.Entrega;
import entities.Lavoura;
import entities.Planta;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import telas.manutencao.ManutencaoLavoura;
import telas.manutencao.PanelAplicacao;
import telas.manutencao.PanelLavoura;
import telas.manutencao.TelaEntrega;

/**
 *
 * @author itzfeltrin
 */
public class ListagemLavouraDetalhada extends javax.swing.JFrame {

    public Lavoura lavoura;
    public Double valorTotal = 0.00;
    
    public ListagemLavouraDetalhada(Lavoura lavoura) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        this.lavoura = lavoura;
        lblNome.setText(lavoura.nome);
        atualizarTabelaAplicacao();
        atualizarTabelaProdutividade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutividade = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAplicacoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JLabel();
        btnNovaEntrega = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tblProdutividade.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblProdutividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProdutividade.setRowHeight(25);
        tblProdutividade.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblProdutividade.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblProdutividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProdutividadeMousePressed(evt);
            }
        });
        tblProdutividade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblProdutividadeKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutividade);

        tblAplicacoes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblAplicacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAplicacoes.setRowHeight(25);
        tblAplicacoes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblAplicacoes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblAplicacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAplicacoesMousePressed(evt);
            }
        });
        tblAplicacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAplicacoesKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblAplicacoes);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Produtividade");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Aplicações de Defensivos");

        btnNovo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnNovo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnNovo.setText("NOVA");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
        });

        btnNovaEntrega.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnNovaEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNovaEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btnNovaEntrega.setText("NOVA");
        btnNovaEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovaEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovaEntregaMouseClicked(evt);
            }
        });

        lblValorTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("TOTAL:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNovaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
        ManutencaoLavoura ml = new ManutencaoLavoura();        
        ml.tabbedPane.setEnabledAt(1, true);
        ml.tabbedPane.setSelectedIndex(1);
        PanelLavoura pl = (PanelLavoura) ml.tabbedPane.getComponentAt(0);
        pl.setLavouraToAddAplicacao(this, this.lavoura);
        ml.setVisible(true);
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnNovaEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovaEntregaMouseClicked
        TelaEntrega te = new TelaEntrega();
        te.setLavoura(this, this.lavoura);
        te.setVisible(true);
    }//GEN-LAST:event_btnNovaEntregaMouseClicked

    private void tblProdutividadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutividadeMousePressed
        if (evt.getClickCount() == 2) {
            //obtem a linha selecionada
            int linhaSelecionada = tblProdutividade.getSelectedRow();
            //obtem a chave primária            
            Integer codigo = Integer.parseInt(tblProdutividade.getValueAt(linhaSelecionada, 0).toString()); //pk está na coluna 0                        
            String tipo = tblProdutividade.getValueAt(linhaSelecionada, 1).toString();            
            String cultivar = tblProdutividade.getValueAt(linhaSelecionada, 2).toString();     
            int safra = Integer.parseInt(tblProdutividade.getValueAt(linhaSelecionada, 3).toString());
            int qtdSacas = Integer.parseInt(tblProdutividade.getValueAt(linhaSelecionada, 4).toString());
            String dataEntrega = tblProdutividade.getValueAt(linhaSelecionada, 6).toString();
            try {
                Entrega auxEntrega = new Entrega(this.lavoura, new Planta(tipo, cultivar), safra, qtdSacas, dataEntrega);
                auxEntrega.codigo = codigo;
                TelaEntrega te = new TelaEntrega();
                te.setEntrega(this, auxEntrega);
                te.setVisible(true);
            } catch (Exception ex) {                
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tblProdutividadeMousePressed

    private void tblProdutividadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutividadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if(tblProdutividade.getSelectedRow() >= 0){
                Object[] options = {"Sim", "Não"};
                int opcao = JOptionPane.showOptionDialog(null, "Tem certeza? Todos os dados serão deletados", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                if(opcao == 0){
                    int linhaSelecionada = tblProdutividade.getSelectedRow();        
                    int codigo = Integer.parseInt(tblProdutividade.getValueAt(linhaSelecionada, 0).toString());
                    EntregaDAO.delete(codigo);            
                    atualizarTabelaProdutividade();
                }        
            }
        }
    }//GEN-LAST:event_tblProdutividadeKeyPressed

    private void tblAplicacoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAplicacoesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if(tblAplicacoes.getSelectedRow() >= 0){
                Object[] options = {"Sim", "Não"};
                int opcao = JOptionPane.showOptionDialog(null, "Tem certeza? Todos os dados serão deletados", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                if(opcao == 0){
                    int linhaSelecionada = tblAplicacoes.getSelectedRow();        
                    int codigo = Integer.parseInt(tblAplicacoes.getValueAt(linhaSelecionada, 0).toString());
                    AplicacaoDAO.delete(codigo);            
                    atualizarTabelaAplicacao();
                }        
            }
        }
    }//GEN-LAST:event_tblAplicacoesKeyPressed

    private void tblAplicacoesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAplicacoesMousePressed
        if (evt.getClickCount() == 2) {
            //obtem a linha selecionada
            int linhaSelecionada = tblAplicacoes.getSelectedRow();
            //obtem a chave primária            
            Integer codigo = Integer.parseInt(tblAplicacoes.getValueAt(linhaSelecionada, 0).toString()); //pk está na coluna 0                        
            String classe = tblAplicacoes.getValueAt(linhaSelecionada, 1).toString();
            String nome = tblAplicacoes.getValueAt(linhaSelecionada, 2).toString();
            String data = tblAplicacoes.getValueAt(linhaSelecionada, 3).toString();
            String osbervacao = tblAplicacoes.getValueAt(linhaSelecionada, 4).toString();
            Double dose = Double.parseDouble(tblAplicacoes.getValueAt(linhaSelecionada, 5).toString());
            Double valor = Double.parseDouble(tblAplicacoes.getValueAt(linhaSelecionada, 6).toString());
            try {
                Defensivo auxDefensivo = new Defensivo(nome, classe);
                Aplicacao auxAplicacao = new Aplicacao(data, osbervacao, this.lavoura);
                auxAplicacao.codigo = codigo;
                AplicacaoDefensivo auxAplicacaoDefensivo = new AplicacaoDefensivo(auxAplicacao, auxDefensivo, valor, dose);
                ManutencaoLavoura ml = new ManutencaoLavoura();        
                ml.tabbedPane.setEnabledAt(1, true);
                ml.tabbedPane.setSelectedIndex(1);
                PanelLavoura pl = (PanelLavoura) ml.tabbedPane.getComponentAt(0);
                PanelAplicacao pa = (PanelAplicacao) ml.tabbedPane.getComponentAt(1);
                pl.setLavouraToAddAplicacao(this, this.lavoura);
                pa.setAplicacaoToEdit(this, auxAplicacao, auxAplicacaoDefensivo, auxDefensivo);
                ml.setVisible(true);
            } catch (Exception ex) {                
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tblAplicacoesMousePressed

    public void atualizarTabelaAplicacao() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        modelo.addColumn("Cód. Aplicação");
        modelo.addColumn("Classe");
        modelo.addColumn("Nome");
        modelo.addColumn("Data");        
        modelo.addColumn("Observação");
        modelo.addColumn("Dose");
        modelo.addColumn("Valor");
        List<String[]> resultados = AplicacaoDefensivoDAO.consult(this.lavoura);
        this.valorTotal = 0.00;
        for (String[] linha : resultados) {
            modelo.addRow(linha);
            this.valorTotal += Double.parseDouble(linha[6]);
            lblValorTotal.setText("R$" + String.format("%.2f", this.valorTotal));
            
        }
        tblAplicacoes.setModel(modelo);        
        tblAplicacoes.getColumnModel().getColumn(0).setMaxWidth(65);        
        tblAplicacoes.getColumnModel().getColumn(1).setMaxWidth(125);        
        tblAplicacoes.getColumnModel().getColumn(3).setMaxWidth(125);        
        tblAplicacoes.getColumnModel().getColumn(5).setMaxWidth(65);        
        tblAplicacoes.getColumnModel().getColumn(6).setMaxWidth(65);        
    }
    public void atualizarTabelaProdutividade() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Tipo");
        modelo.addColumn("Cultivar");
        modelo.addColumn("Safra");        
        modelo.addColumn("Qtd. em Sacas");
        modelo.addColumn("Total em Kgs");
        modelo.addColumn("Data Entrega");
        modelo.addColumn("Data Cadastro");
        modelo.addColumn("Data Alteração");
        List<String[]> resultados = EntregaDAO.consult(this.lavoura);
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tblProdutividade.setModel(modelo);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemLavouraDetalhada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ListagemLavouraDetalhada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnNovaEntrega;
    private javax.swing.JLabel btnNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblAplicacoes;
    private javax.swing.JTable tblProdutividade;
    // End of variables declaration//GEN-END:variables
}
