/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas.listagem;

import DAO.LavouraDAO;
import entities.Lavoura;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import telas.manutencao.ManutencaoDefensivo;
import telas.manutencao.ManutencaoLavoura;
import telas.manutencao.PanelLavoura;

/**
 *
 * @author itzfeltrin
 */
public class ListagemLavoura extends javax.swing.JFrame {

    /**
     * Creates new form ListagemDefensivo
     */
    public ListagemLavoura() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        atualizarTabela();   
        searchFunctionalities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchLavouras = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLavouras = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listagem de Lavouras");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Filtrar:");

        txtSearchLavouras.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        tblLavouras.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tblLavouras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLavouras.setRowHeight(25);
        tblLavouras.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblLavouras.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblLavouras.setShowGrid(true);
        tblLavouras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLavourasMousePressed(evt);
            }
        });
        tblLavouras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblLavourasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLavouras);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        jLabel3.setText("NOVA");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchLavouras, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchLavouras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        ManutencaoLavoura ml = new ManutencaoLavoura();
        ml.setVisible(true);
        PanelLavoura pl = (PanelLavoura) ml.tabbedPane.getComponentAt(0);
        pl.setLavoura(this, null);
    }//GEN-LAST:event_jLabel3MousePressed

    private void tblLavourasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLavourasMousePressed
        if (evt.getClickCount() == 2) {
            //obtem a linha selecionada
            int linhaSelecionada = tblLavouras.getSelectedRow();

            //obtem a chave primária            
            Integer codigo = Integer.parseInt(tblLavouras.getValueAt(linhaSelecionada, 0).toString()); //pk está na coluna 0                        
            String nome = tblLavouras.getValueAt(linhaSelecionada, 1).toString();            
            Double extensao = Double.parseDouble(tblLavouras.getValueAt(linhaSelecionada, 2).toString());            
            try {
                Lavoura aux = new Lavoura(nome, extensao);
                aux.codigo = codigo;
                ManutencaoLavoura ml = new ManutencaoLavoura();
                PanelLavoura pl = (PanelLavoura) ml.tabbedPane.getComponentAt(0);
                pl.setLavoura(this, aux);
                ml.setVisible(true);                
                //ListagemLavouraDetalhada lld = new ListagemLavouraDetalhada(nome);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tblLavourasMousePressed

    private void tblLavourasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLavourasKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE) {
            if(tblLavouras.getSelectedRow() >= 0){
                Object[] options = {"Sim", "Não"};
                int opcao = JOptionPane.showOptionDialog(null, "Tem certeza? Todos os dados referentes também serão deletados", "Alerta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                if(opcao == 0){
                    int linhaSelecionada = tblLavouras.getSelectedRow();        
                    int codigo = Integer.parseInt(tblLavouras.getValueAt(linhaSelecionada, 0).toString());
                    LavouraDAO.delete(codigo);            
                    atualizarTabela();
                }        
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_F1) {
            if(tblLavouras.getSelectedRow() >= 0){                
                try {
                    int linhaSelecionada = tblLavouras.getSelectedRow();        
                    int codigo = Integer.parseInt(tblLavouras.getValueAt(linhaSelecionada, 0).toString());
                    String nome = tblLavouras.getValueAt(linhaSelecionada, 1).toString();
                    Double extensao = Double.parseDouble(tblLavouras.getValueAt(linhaSelecionada, 2).toString());
                    Lavoura aux;
                    aux = new Lavoura(nome, extensao);
                    aux.codigo = codigo;
                    ListagemLavouraDetalhada lld = new ListagemLavouraDetalhada(aux);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_tblLavourasKeyPressed

    public void atualizarTabela() {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Nome");
        modelo.addColumn("Extensão em Hectares");        
        List<String[]> resultados = LavouraDAO.consult();
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tblLavouras.setModel(modelo);
        tblLavouras.getColumnModel().getColumn(0).setMaxWidth(65);
    }
    
    public void search(String text) {
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        modelo.addColumn("Código");
        modelo.addColumn("Nome");
        modelo.addColumn("Extensão em Hectares");        
        List<String[]> resultados = LavouraDAO.search(text);
        for (String[] linha : resultados) {
            modelo.addRow(linha);
        }
        tblLavouras.setModel(modelo);
        tblLavouras.getColumnModel().getColumn(0).setMaxWidth(65);
    }
    
    public void searchFunctionalities() {
        txtSearchLavouras.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                search(txtSearchLavouras.getText());
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                if(txtSearchLavouras.getText().length() == 0) {
                    atualizarTabela();
                }
                else {
                    search(txtSearchLavouras.getText());
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                System.out.println("cc");
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemLavoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemLavoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemLavoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemLavoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemLavoura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLavouras;
    private javax.swing.JTextField txtSearchLavouras;
    // End of variables declaration//GEN-END:variables
}
